### ISSUE TITLE
Package doesn't work with `--disable-proto=delete`

### ISSUE THREAD

**Issue by dsherret** [inspect-js/typed-array-byte-offset#4]
When I run the unit tests with `NODE_OPTIONS=--disable-proto=delete` I get the following error:

```
$ npm run tests-only

> typed-array-byte-offset@1.0.2 tests-only
> NODE_OPTIONS=--disable-proto=delete nyc tape 'test/**/*.js'

/mnt/v/typed-array-byte-offset/index.js:6
++cov_1i9ps04zcs.s[16];descriptor=gOPD(superProto,'byteOffset');}else{++cov_1i9ps04zcs.b[3][1];}// Opera 12.16 has a magic byteOffset data property on instances AND on Proto
                                  ^

TypeError: Cannot convert undefined or null to object
    at getOwnPropertyDescriptor (<anonymous>)
    at /mnt/v/typed-array-byte-offset/index.js:6:35
    at forEachArray (/mnt/v/typed-array-byte-offset/node_modules/for-each/index.js:12:17)
    at forEach (/mnt/v/typed-array-byte-offset/node_modules/for-each/index.js:54:9)
    at Object.<anonymous> (/mnt/v/typed-array-byte-offset/index.js:1:7537)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module.replacementCompile (/mnt/v/typed-array-byte-offset/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/mnt/v/typed-array-byte-offset/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/mnt/v/typed-array-byte-offset/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (node:internal/modules/cjs/loader:1206:32)

Node.js v20.12.2
```

I think this is because the has-proto only checks if `__proto__` is allowed on object creation and not after the fact?

**Comment by ljharb** [comment]
You're right; the semantics of `has-proto` are definitely "can be set in an object literal" and not "the accessor exists".

I'm not sure I care to support this particular node flag - it's just not reasonable to enable it with how many parts of the ecosystem it breaks. It wouldn't be hard to add, but it'd add an extra dependency on `reflect.getprototypeof`.

**Comment by dsherret** [comment]
> It wouldn't be hard to add, but it'd add an extra dependency

Would you be willing to support this scenario for where the `Reflect` global exists so a dependency doesn't need to be added? Also, it seems the dependency on `has-proto` could be removed since it's not checking the right thing?

**Comment by ljharb** [comment]
Indeed, it'd remove the has-proto dep. My robustness constraints don't allow me to solely rely on Reflect, though - I'll probably end up adding the dep.

**Comment by dsherret** [comment]
Thanks! Not relying on `__proto__` slowly moves the ecosystem in a better place.

**Comment by ljharb** [comment]
I think the accessor is fine as-is, personally, and removing it isn't "better", but correctness does matter, and it was clearly incorrect.

v1.0.3 will be published later today.

**Comment by ljharb** [comment]
v1.0.3 is released. I'll also add some regression tests.
